AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Serverless Composer repository for private PHP packages hosted on Github
Resources:
  ApiGatewayApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: prod
      DefinitionUri: s3://{AWS_S3_BUCKET}/{S3_SWAGGER_YAML_KEY}
      Variables:
        ServerlessExpressLambdaFunctionName:
          Ref: {AWS_LAMBDA_FUNCTION_NAME}

  {AWS_LAMBDA_FUNCTION_NAME}:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: nodejs8.10
      Handler: server.handler
      CodeUri: s3://{AWS_S3_BUCKET}/{S3_LAMBDA_PACKAGE_ZIP_KEY}
      Timeout: 30
      MemorySize: 1024
      Role:
        Fn::GetAtt:
        - LambdaExecutionRole
        - Arn
      Environment:
        Variables:
          NODE_ENV: production
          AWS_S3_BUCKET: {AWS_S3_BUCKET}
          GITHUB_TOKEN: {GITHUB_TOKEN}
      Events:
        ProxyApiRoot:
          Type: Api
          Properties:
            Path: /
            Method: ANY
            RestApiId:
              Ref: ApiGatewayApi
        ProxyApiGreedy:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: ANY
            RestApiId:
              Ref: ApiGatewayApi
        SqsQueueEvent:
          Type: SQS
          Properties:
            BatchSize: 10
            Queue:
              Fn::GetAtt:
              - PackageQueue
              - Arn

  PackageQueue:
    Type: AWS::SQS::Queue
    Properties:
      VisibilityTimeout: 60

  LambdaApiGatewayExecutionPermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      Principal: apigateway.amazonaws.com
      FunctionName:
        Fn::GetAtt:
        - {AWS_LAMBDA_FUNCTION_NAME}
        - Arn
      SourceArn:
        Fn::Join:
        - ''
        - - 'arn:aws:execute-api:'
          - Ref: AWS::Region
          - ':'
          - Ref: AWS::AccountId
          - ':'
          - Ref: ApiGatewayApi
          - /*/*

  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      Path: /
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          Action: sts:AssumeRole
          Effect: Allow
          Principal:
            Service: lambda.amazonaws.com
      Policies:
      - PolicyName: LogsAccess
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
          - Action:
            - logs:CreateLogGroup
            - logs:CreateLogStream
            - logs:PutLogEvents
            Effect: Allow
            Resource:
              Fn::Join:
              - ''
              - - 'arn:aws:logs:'
                - Ref: AWS::Region
                - ':'
                - Ref: AWS::AccountId
                - ':'
                - '*'
      - PolicyName: SQSAccess
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
          - Action:
            - sqs:SendMessage
            - sqs:ReceiveMessage
            - sqs:DeleteMessage
            - sqs:GetQueueAttributes
            Effect: Allow
            Resource:
              Fn::Join:
              - ''
              - - 'arn:aws:sqs:'
                - Ref: AWS::Region
                - ':'
                - Ref: AWS::AccountId
                - ':'
                - '*'
      - PolicyName: S3AccessList
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
          - Action:
            - s3:ListBucket
            Effect: Allow
            Resource:
              Fn::Join:
              - ''
              - - 'arn:aws:s3:::'
                - {AWS_S3_BUCKET}
      - PolicyName: S3Access
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
          - Action:
            - s3:GetObject
            - s3:PutObject
            - s3:DeleteObject
            Effect: Allow
            Resource:
              Fn::Join:
              - ''
              - - 'arn:aws:s3:::'
                - {AWS_S3_BUCKET}
                - '/*'

Outputs:
  ApiGatewayApiConsoleUrl:
    Description: Console URL for the API Gateway API's Stage.
    Value:
      Fn::Join:
      - ''
      - - https://
        - Ref: AWS::Region
        - .console.aws.amazon.com/apigateway/home?region=
        - Ref: AWS::Region
        - '#/apis/'
        - Ref: ApiGatewayApi
        - /stages/prod

  ApiUrl:
    Description: Invoke URL for your API. Clicking this link will perform a GET request
      on the root resource of your API.
    Value:
      Fn::Join:
      - ''
      - - https://
        - Ref: ApiGatewayApi
        - .execute-api.
        - Ref: AWS::Region
        - .amazonaws.com/prod/

  LambdaFunctionConsoleUrl:
    Description: Console URL for the Lambda Function.
    Value:
      Fn::Join:
      - ''
      - - https://
        - Ref: AWS::Region
        - .console.aws.amazon.com/lambda/home?region=
        - Ref: AWS::Region
        - '#/functions/'
        - Ref: {AWS_LAMBDA_FUNCTION_NAME}

  SqsConsoleUrl:
    Description: Console URL for the SQS.
    Value:
      Fn::Join:
      - ''
      - - https://
        - Ref: AWS::Region
        - .console.aws.amazon.com/sqs/home?region=
        - Ref: AWS::Region
